apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-react-app
  namespace: prod-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: regaipaydogdu/react-app
        resources:
          requests:
              memory: "128Mi"
              cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
