apiVersion: v1
kind: Service
metadata:
  name: service-react-app
spec:
  type : NodePort
  selector:
    app: react-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
